apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-ui
  template:
    metadata:
      labels:
        app: url-shortener-ui
    spec:
      containers:
      - name: ui
        image: url-shortener-ui:latest # Tag updated via CI
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
