resources:
- deployment-ui.yaml
- service-ui.yaml
- rollout-api.yaml
- service-api.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: url-shortener-api
  newName: 381940662325.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-api
  newTag: f4f3baa83097e1d7c894d734add7b9d7eac14a4f
- name: url-shortener-ui
  newName: 381940662325.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-ui
  newTag: f4f3baa83097e1d7c894d734add7b9d7eac14a4f
